export const IMG_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const restrauntList = [
  {
    name: "Hotel Prashanth",
    cuisines: ["South Indian", "North Indian"],
    cloudinaryImageId: "gy8xbjj2f059qw7cwcis",
    avgRating: "3.7",
  },
  {
    name: "Hotel Empire",
    cuisines: ["North Indian", "Kebabs", "Biryani"],
    cloudinaryImageId: "ervram6kki8b97it2ulr",
    avgRating: "4.0",
  },
  {
    name: "Meghana Foods",
    cuisines: [
      "Biryani",
      "Andhra",
      "South Indian",
      "North Indian",
      "Chinese",
      "Seafood",
    ],
    cloudinaryImageId: "slheenytwb3iaypqf4yd",
    avgRating: "4.4",
  },
  {
    name: "Wayanadans Cafe",
    cuisines: [
      "Kerala",
      "South Indian",
      "Chinese",
      "Desserts",
      "Beverages",
      "Bakery",
      "Seafood",
    ],
    cloudinaryImageId: "qwukwsaq4alydxjq91a7",
    avgRating: "4.1",
  },
  {
    name: "Karnataka biryani paradise",
    cuisines: ["Biryani", "Chinese"],
    cloudinaryImageId: "vdn0gihrrqfi5jymkrpb",
    avgRating: "3.5",
  },
  {
    name: "Istah - The Mediterranean Way",
    cuisines: [
      "Arabian",
      "Biryani",
      "Mediterranean",
      "Lebanese",
      "Snacks",
      "Beverages",
    ],
    cloudinaryImageId: "67d4a416bf932f850b0a15ad33aae762",
    avgRating: "4.2",
  },
  {
    name: "Kritunga Restaurant",
    cuisines: ["Andhra", "Biryani"],
    cloudinaryImageId: "pqk6wh0nslnekrom8jxf",
    avgRating: "3.9",
  },
  {
    name: "Chikpet Donne Biryani House Palace Guttahalli",
    cuisines: ["Biryani", "South Indian"],
    cloudinaryImageId: "ckpftg1mcfxnlm392vvj",
    avgRating: "4.0",
  },
  {
    name: "Truffles",
    cuisines: ["American", "Desserts", "Italian", "Continental"],
    cloudinaryImageId: "cd832b6167eb9f88aeb1ccdebf38d942",
    avgRating: "4.4",
  },
  {
    name: "Chicking",
    cuisines: [
      "American",
      "Grill",
      "Fast Food",
      "Snacks",
      "Pizzas",
      "Mexican",
      "Beverages",
    ],
    cloudinaryImageId: "joazw8wzy9tf4ejdcxae",
    avgRating: "4.1",
  },
  {
    name: "Donne Biriyani Angadi Mane",
    cuisines: ["Biryani", "South Indian"],
    cloudinaryImageId: "fijvy8eusvpo0jkqiayn",
    avgRating: "3.7",
  },
  {
    name: "Hotel Kadamba Veg",
    cuisines: ["South Indian", "North Indian", "Chinese", "Sweets"],
    cloudinaryImageId: "ywdpqvhsmaru4uef8szm",
    avgRating: "4.3",
  },
  {
    name: "Burger King",
    cuisines: ["Burgers", "American"],
    cloudinaryImageId: "dmi0pdcwjddzhlboew9g",
    avgRating: "4.2",
  },
  {
    name: "Absolute Chinese",
    cuisines: ["Chinese", "Thai", "Snacks"],
    cloudinaryImageId: "hsif475h4e4iy7odmtea",
    avgRating: "4.1",
  },
  {
    name: "Shanthi Sagar",
    cuisines: ["South Indian", "North Indian", "Chinese", "Chaat"],
    cloudinaryImageId: "lopeqgx2ufrnk63unoal",
    avgRating: "4.2",
  },
  {
    name: "New Taj Darbar",
    cuisines: ["Biryani", "Indian", "Chinese", "Tandoor", "Seafood"],
    cloudinaryImageId: "nfieyqgxk1omknxfbluj",
    avgRating: "3.5",
  },
  {
    name: "EatFit",
    cuisines: [
      "Healthy Food",
      "Pizzas",
      "North Indian",
      "Thalis",
      "Biryani",
      "Chinese",
    ],
    cloudinaryImageId: "c769d3b4bb5a6a6a7d36eb28eacd00aa",
    avgRating: "4.2",
  },
  {
    name: "Chai Point",
    cuisines: [
      "Bakery",
      "Beverages",
      "Maharashtrian",
      "Snacks",
      "Street Food",
      "South Indian",
      "Punjabi",
    ],
    cloudinaryImageId: "cjmbqxgund7syshvymj7",
    avgRating: "4.2",
  },
  {
    name: "Chikpet Donne Biryani House - Vijayanagar",
    cuisines: ["Biryani", "South Indian"],
    cloudinaryImageId: "cpbq1uck4icuhdqvuwb0",
    avgRating: "4.1",
  },
  {
    name: "Baskin Robbins",
    cuisines: ["Desserts"],
    cloudinaryImageId: "lfhhvuxclvfuwle01xtr",
    avgRating: "4.3",
  },
  {
    name: "Al-Bek",
    cuisines: [
      "Tandoor",
      "Mughlai",
      "Arabian",
      "North Indian",
      "Chinese",
      "Biryani",
      "Snacks",
    ],
    cloudinaryImageId: "oljtucnsnbz9xuvo3qpv",
    avgRating: "4.0",
  },
  {
    name: "Siddique kabab centre",
    cuisines: ["Chinese", "Arabian", "Tandoor"],
    cloudinaryImageId: "kmcceh3ztsyh8wcsfsgi",
    avgRating: "4.1",
  },
  {
    name: "Le Arabia",
    cuisines: [
      "Arabian",
      "Beverages",
      "Biryani",
      "Chinese",
      "Desserts",
      "Seafood",
      "Hyderabadi",
      "Ice Cream",
      "Afghani",
      "Grill",
      "Tandoor",
    ],
    cloudinaryImageId: "s2tcja1qsmkhkxkcly7z",
    avgRating: "3.8",
  },
  {
    name: "Corner House Ice Cream",
    cuisines: ["Ice Cream", "Desserts"],
    cloudinaryImageId: "mtlwxk3sbjlc8ged0uaj",
    avgRating: "4.7",
  },
  {
    name: "Donne Biriyani Angadi Mane",
    cuisines: ["Biryani", "South Indian"],
    cloudinaryImageId: "e9rc8znfnb8v9ygwrobq",
    avgRating: "3.9",
  },
  {
    name: "Nandhana Palace",
    cuisines: ["Biryani", "Andhra", "South Indian", "North Indian"],
    cloudinaryImageId: "n1ibhuge75vzzhu8db8v",
    avgRating: "4.3",
  },
  {
    name: "Malgudi's Donne Biriyani-Mathikere",
    cuisines: ["Biryani"],
    cloudinaryImageId: "tyci8nq9f8e2zntyrsp2",
    avgRating: "4.3",
  },
  {
    name: "Leon's - Burgers & Wings (Leon Grill)",
    cuisines: ["American", "Snacks", "Turkish", "Portuguese", "Continental"],
    cloudinaryImageId: "kg3cw4brsjuvwzlgkzaf",
    avgRating: "4.1",
  },
  {
    name: "Donne Biriyani Mane",
    cuisines: ["Biryani"],
    cloudinaryImageId: "e3ua2ejzc7hmaflx7yws",
    avgRating: "3.6",
  },
  {
    name: "Onesta",
    cuisines: ["Italian", "Desserts", "Pizzas", "American", "Snacks"],
    cloudinaryImageId: "wxaxghihutxrekuuurn7",
    avgRating: "3.8",
  },
  {
    name: "Domino's Pizza",
    cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    cloudinaryImageId: "nnvcjubdqvwc7zovln6j",
    avgRating: "4.3",
  },
  {
    name: "Imperial Restaurant",
    cuisines: [
      "Tandoor",
      "Biryani",
      "Kerala",
      "South Indian",
      "North Indian",
      "Chinese",
      "Beverages",
    ],
    cloudinaryImageId: "hzbr9gwqfejghaxuhsvc",
    avgRating: "4.1",
  },
  {
    name: "Hotel Moon Light",
    cuisines: ["Indian", "Chinese", "Biryani", "Tandoor"],
    cloudinaryImageId: "htl5oi2b8cd3acugbn52",
    avgRating: "4.3",
  },
  {
    name: "La Pino'z Pizza",
    cuisines: ["Pizzas", "Italian", "Pastas", "Mexican", "Desserts"],
    cloudinaryImageId: "57a56b68fa69d5fa79443df6d7444521",
    avgRating: "3.9",
  },
  {
    name: "Gowdru Biriyani Mane",
    cuisines: ["Biryani"],
    cloudinaryImageId: "vzpaxotltxdgcp3gsxkj",
    avgRating: "3.2",
  },
  {
    name: "Le Arabia Restaurant",
    cuisines: ["Arabian", "North Indian", "Chinese", "Beverages", "Ice Cream"],
    cloudinaryImageId: "mwxhhv8xvbokqdmm6uk4",
    avgRating: "3.8",
  },
  {
    name: "Restaurant IHA",
    cuisines: ["Indian"],
    cloudinaryImageId: "ezvqyv9or24ruy9qdztw",
    avgRating: "3.3",
  },
  {
    name: "Sultan Rolls & Sandwiches",
    cuisines: ["Chinese", "Snacks", "Biryani"],
    cloudinaryImageId: "ymy4sgwaozqxhp1hhqcd",
    avgRating: "3.8",
  },
  {
    name: "Namaste Veg",
    cuisines: ["South Indian", "Snacks"],
    cloudinaryImageId: "u3w9mp7dikehkvmuzkht",
    avgRating: "4.7",
  },
  {
    name: "Elite Restaurant",
    cuisines: [
      "Chinese",
      "South Indian",
      "North Indian",
      "Continental",
      "American",
      "Desserts",
      "Kerala",
      "Beverages",
      "Mughlai",
      "Seafood",
      "Hyderabadi",
      "Singaporean",
    ],
    cloudinaryImageId: "n8odvjudjeagul2s9ktb",
    avgRating: "3.8",
  },
  {
    name: "WarmOven Cake & Desserts",
    cuisines: ["Bakery", "Desserts", "Ice Cream", "Beverages"],
    cloudinaryImageId: "e938fb5f416cc2c28b4b519cf27b04cc",
    avgRating: "4.4",
  },
  {
    name: "Natural Ice Cream",
    cuisines: ["Ice Cream", "Desserts"],
    cloudinaryImageId: "lgmltaoetfdmf9nhflix",
    avgRating: "4.7",
  },
  {
    name: "The Cake Deluxe",
    cuisines: ["Bakery", "Desserts"],
    cloudinaryImageId: "zgft6bgx1vm1bmqqq1gi",
    avgRating: "3.8",
  },
  {
    name: "Bakingo",
    cuisines: ["Bakery", "Desserts", "Beverages", "Snacks"],
    cloudinaryImageId: "qwbqggsxzw86vgk60c9c",
    avgRating: "4.1",
  },
  {
    name: "T's 21 Spice Biryani",
    cuisines: [
      "Andhra",
      "Biryani",
      "Hyderabadi",
      "South Indian",
      "Indian",
      "Beverages",
    ],
    cloudinaryImageId: "itzlucsdbqyljn07ucdy",
    avgRating: "4.1",
  },
];
